services:
  orvix-db:
    image: ankane/pgvector:latest
    container_name: orvix_postgres
    environment:
      POSTGRES_USER: orvix_admin
      POSTGRES_PASSWORD: orvix_password_dev
      POSTGRES_DB: orvixflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: orvix_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - orvix-db
  orvix-api:
    build:
      context: .
      dockerfile: OrvixFlow.Api/Dockerfile
    container_name: orvix_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=orvix-db;Database=orvixflow;Username=orvix_admin;Password=orvix_password_dev
      Frontend__BaseUrl: http://localhost:3000
      AutomationKey: ${AUTOMATION_KEY}
      Jwt__Secret: ${JWT_SECRET}
      Jwt__Issuer: ${JWT_ISSUER:-orvixflow}
      Jwt__Audience: ${JWT_AUDIENCE:-orvixflow-web}
      AI__Provider: OpenAI
      AI__OpenAI__ApiKey: ${AI_OPENAI_API_KEY}
      Automation__N8nBaseUrl: ${N8N_BASE_URL:-http://orvix-n8n:5678}
    env_file:
      - .env
    depends_on:
      - orvix-db
      - n8n
    restart: unless-stopped
    volumes:
      - uploads_data:/app/uploads

  orvix-web:
    build:
      context: ./orvixflow-web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8080
    container_name: orvix_web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      AUTH_TRUST_HOST: "true"
      NEXT_PUBLIC_API_URL: http://localhost:8080
      INTERNAL_API_URL: http://orvix-api:8080
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      AZURE_AD_CLIENT_ID: ${AZURE_AD_CLIENT_ID}
      AZURE_AD_CLIENT_SECRET: ${AZURE_AD_CLIENT_SECRET}
    env_file:
      - .env
    depends_on:
      - orvix-api
    restart: unless-stopped

volumes:
  pgdata:
  n8n_data:
  uploads_data:
