// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OrvixFlow.Infrastructure.Data;
using Pgvector;

#nullable disable

namespace OrvixFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvaluatedCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InboxEventId");

                    b.ToTable("ActionRequests");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.BillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("BillingSubscriptions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.InboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text");

                    b.Property<string>("WebhookCallbackPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Email");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "ModuleDefinitionId", "DepartmentId", "UserId", "Scope");

                    b.ToTable("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ModuleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 363, DateTimeKind.Utc).AddTicks(7073),
                            DisplayName = "Doc-Intel",
                            IsActive = true,
                            IsOperational = false,
                            Key = "doc-intel",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(3963),
                            DisplayName = "Finance-Flow",
                            IsActive = true,
                            IsOperational = false,
                            Key = "finance-flow",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(3984),
                            DisplayName = "Inbox-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            Key = "inbox-guardian",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4118),
                            DisplayName = "Lead-Qualifier",
                            IsActive = true,
                            IsOperational = false,
                            Key = "lead-qualifier",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4124),
                            DisplayName = "Legal-Scribe",
                            IsActive = true,
                            IsOperational = false,
                            Key = "legal-scribe",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4129),
                            DisplayName = "Data-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            Key = "data-guardian",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4162),
                            DisplayName = "SOP-Generator",
                            IsActive = true,
                            IsOperational = false,
                            Key = "sop-generator",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4167),
                            DisplayName = "Metered-Billing",
                            IsActive = true,
                            IsOperational = true,
                            Key = "metered-billing",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2026, 3, 26, 8, 7, 33, 364, DateTimeKind.Utc).AddTicks(4173),
                            DisplayName = "Audit-Log",
                            IsActive = true,
                            IsOperational = true,
                            Key = "audit-log",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanConfigure")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageIntegrations")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePrompts")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTest")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleAssignmentId");

                    b.ToTable("ModulePermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "MetricType", "OccurredAt");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserCompanyMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserCompanyMembershipId");

                    b.HasIndex("UserId", "CompanyId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartmentMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenUsage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkflowLogs");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoExecute")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConfidenceThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkflowPolicies");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.InboxEvent", "InboxEvent")
                        .WithMany()
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrvixFlow.Core.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ModuleAssignment", "ModuleAssignment")
                        .WithMany("PermissionGrants")
                        .HasForeignKey("ModuleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleAssignment");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserDepartmentMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("UserMemberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.UserCompanyMembership", null)
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserCompanyMembershipId");

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Navigation("PermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserDepartmentMemberships");

                    b.Navigation("UserMemberships");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("DepartmentMemberships");

                    b.Navigation("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Navigation("DepartmentMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
