// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OrvixFlow.Infrastructure.Data;
using Pgvector;

#nullable disable

namespace OrvixFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvaluatedCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InboxEventId");

                    b.ToTable("ActionRequests");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.AgentPersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomSignOff")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("AgentPersonas");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.BillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("BillingSubscriptions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.CompanySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PendingChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PendingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("PendingPlanId");

                    b.HasIndex("PlanTemplateId");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.DraftFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EditDistance")
                        .HasColumnType("numeric");

                    b.Property<string>("FinalHumanDraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalDraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionRequestId");

                    b.HasIndex("TenantId", "ActionRequestId");

                    b.ToTable("DraftFeedbacks");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.InboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text");

                    b.Property<string>("WebhookCallbackPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Email");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "RawContent" });

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmbeddingVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EmbeddingVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EmbeddingVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBaseDocuments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.MailboxConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("N8nCredentialId")
                        .HasColumnType("text");

                    b.Property<string>("N8nWorkflowId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("MailboxConnections");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "ModuleDefinitionId", "DepartmentId", "UserId", "Scope");

                    b.ToTable("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ModuleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 629, DateTimeKind.Utc).AddTicks(3889),
                            Description = "",
                            DisplayName = "Doc-Intel",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "doc-intel",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1570),
                            Description = "",
                            DisplayName = "Finance-Flow",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "finance-flow",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1626),
                            Description = "",
                            DisplayName = "Inbox-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "inbox-guardian",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1658),
                            Description = "",
                            DisplayName = "Lead-Qualifier",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "lead-qualifier",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1689),
                            Description = "",
                            DisplayName = "Legal-Scribe",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "legal-scribe",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1722),
                            Description = "",
                            DisplayName = "Data-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "data-guardian",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1752),
                            Description = "",
                            DisplayName = "SOP-Generator",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "sop-generator",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1781),
                            Description = "",
                            DisplayName = "Metered-Billing",
                            IsActive = true,
                            IsOperational = true,
                            IsPremium = false,
                            Key = "metered-billing",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 631, DateTimeKind.Utc).AddTicks(1811),
                            Description = "",
                            DisplayName = "Audit-Log",
                            IsActive = true,
                            IsOperational = true,
                            IsPremium = false,
                            Key = "audit-log",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanConfigure")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageIntegrations")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePrompts")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTest")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleAssignmentId");

                    b.ToTable("ModulePermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanEntitlements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxApiRequestsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaxKnowledgeBases")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonthlyTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageMb")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanTemplateId")
                        .IsUnique();

                    b.ToTable("PlanEntitlements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 500,
                            MaxKnowledgeBases = 1,
                            MaxMonthlyTokens = 50000,
                            MaxStorageMb = 100,
                            PlanTemplateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 1000,
                            MaxKnowledgeBases = 5,
                            MaxMonthlyTokens = 100000,
                            MaxStorageMb = 500,
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 5000,
                            MaxKnowledgeBases = 25,
                            MaxMonthlyTokens = 500000,
                            MaxStorageMb = 5120,
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 20000,
                            MaxKnowledgeBases = 100,
                            MaxMonthlyTokens = 2000000,
                            MaxStorageMb = 51200,
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 100000,
                            MaxKnowledgeBases = 1000,
                            MaxMonthlyTokens = 10000000,
                            MaxStorageMb = 512000,
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanModuleInclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("PlanTemplateId", "ModuleDefinitionId")
                        .IsUnique();

                    b.ToTable("PlanModuleInclusions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("196a88fa-08da-4c8e-90bd-1a9c356ede43"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 643, DateTimeKind.Utc).AddTicks(8307),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("d2c3ab76-4d33-442f-987d-dfdefa113a6e"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1079),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("a887af5f-5baa-4132-9a8a-3b75a8d77fc4"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1108),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("fdf21d0f-9270-4d55-af89-dae97e40d1a6"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1135),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("849abdae-3f67-42ec-9c86-f60f5d812255"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1157),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("08f7f4f4-0691-4007-9257-e4eebf746654"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1182),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("d9cfc5e9-bc40-4acb-9c42-ac7923637c9b"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1208),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("bafe0c1c-edbb-420e-9171-0507f4bc6a4f"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1230),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("df2df6d0-32b1-47fc-9e03-7979c00eb609"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1253),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("ac311e2f-3564-44ad-9714-b556efefd035"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1277),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("a39f2612-2862-416f-a051-b36aee5e1489"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1301),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("b62d61f0-d631-4382-b9c4-07a7ca0117fe"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1324),
                            ModuleDefinitionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("97721cb6-1854-4525-aef1-2899884ab5a4"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1348),
                            ModuleDefinitionId = new Guid("77777777-7777-7777-7777-777777777777"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("da19a03f-699a-4155-8fb0-77cd1e7e529e"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1371),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("882ed7df-5285-49dc-ab3e-5b470ba9de6f"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1398),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("6c80e6e6-2c76-439c-9077-685f38dc2056"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1421),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("446c894f-d7c5-4714-87d5-975695836abc"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1442),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("2e48dadb-6908-4377-82cd-0a0ca53d01c9"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1465),
                            ModuleDefinitionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("2b9c1a2e-b902-40be-805b-a3eff211b05e"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1493),
                            ModuleDefinitionId = new Guid("77777777-7777-7777-7777-777777777777"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("b27057d3-76b5-4c12-83f1-5fd441c04e21"),
                            CreatedAt = new DateTime(2026, 4, 1, 13, 26, 0, 644, DateTimeKind.Utc).AddTicks(1514),
                            ModuleDefinitionId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrialAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LegacyLocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyPriceCents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<int>("YearlyPriceCents")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PlanTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For individuals testing AI workflows.",
                            IsActive = true,
                            IsFree = true,
                            IsTrialAllowed = false,
                            LegacyLocked = false,
                            MaxSeats = 2,
                            MonthlyPriceCents = 0,
                            Name = "Free",
                            Slug = "free",
                            TrialDays = 0,
                            YearlyPriceCents = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For small teams automating support.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 5,
                            MonthlyPriceCents = 2900,
                            Name = "Starter",
                            Slug = "starter",
                            TrialDays = 14,
                            YearlyPriceCents = 29000
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For growing teams needing more power.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 25,
                            MonthlyPriceCents = 9900,
                            Name = "Growth",
                            Slug = "growth",
                            TrialDays = 14,
                            YearlyPriceCents = 99000
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For large teams with advanced needs.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 100,
                            MonthlyPriceCents = 29900,
                            Name = "Business",
                            Slug = "business",
                            TrialDays = 14,
                            YearlyPriceCents = 299000
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BillingInterval = "Custom",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For large organizations with custom needs.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = false,
                            LegacyLocked = false,
                            MonthlyPriceCents = 0,
                            Name = "Enterprise",
                            Slug = "enterprise",
                            TrialDays = 0,
                            YearlyPriceCents = 0
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "MetricType", "OccurredAt");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserCompanyMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserCompanyMembershipId");

                    b.HasIndex("UserId", "CompanyId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartmentMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenUsage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkflowLogs");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoExecute")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConfidenceThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkflowPolicies");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.InboxEvent", "InboxEvent")
                        .WithMany()
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.CompanySubscription", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PendingPlan")
                        .WithMany()
                        .HasForeignKey("PendingPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("PlanTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PendingPlan");

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.DraftFeedback", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ActionRequest", null)
                        .WithMany()
                        .HasForeignKey("ActionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.KnowledgeBaseDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.MailboxConnection", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrvixFlow.Core.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ModuleAssignment", "ModuleAssignment")
                        .WithMany("PermissionGrants")
                        .HasForeignKey("ModuleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleAssignment");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanEntitlements", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithOne("Entitlements")
                        .HasForeignKey("OrvixFlow.Core.Entities.PlanEntitlements", "PlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanModuleInclusion", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("PlanInclusions")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithMany("ModuleInclusions")
                        .HasForeignKey("PlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleDefinition");

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserDepartmentMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("UserMemberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.UserCompanyMembership", null)
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserCompanyMembershipId");

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Navigation("PermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PlanInclusions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanTemplate", b =>
                {
                    b.Navigation("CompanySubscriptions");

                    b.Navigation("Entitlements");

                    b.Navigation("ModuleInclusions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserDepartmentMemberships");

                    b.Navigation("UserMemberships");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("DepartmentMemberships");

                    b.Navigation("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Navigation("DepartmentMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
