// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using OrvixFlow.Infrastructure.Data;
using Pgvector;

#nullable disable

namespace OrvixFlow.Infrastructure.Data.Migrations.AddImageSupport
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402064342_AddImageSupport")]
    partial class AddImageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DraftResponse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EvaluatedCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InboxEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("PolicyReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InboxEventId");

                    b.ToTable("ActionRequests");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.AgentPersona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomInstructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomSignOff")
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("AgentPersonas");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.AuditTrail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionDetails")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.BillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CurrentPlan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeCustomerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StripeSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.ToTable("BillingSubscriptions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.CompanySubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentPeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PendingChangeAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PendingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId")
                        .IsUnique();

                    b.HasIndex("PendingPlanId");

                    b.HasIndex("PlanTemplateId");

                    b.ToTable("CompanySubscriptions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.DraftFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActionRequestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("EditDistance")
                        .HasColumnType("numeric");

                    b.Property<string>("FinalHumanDraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OriginalDraft")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActionRequestId");

                    b.HasIndex("TenantId", "ActionRequestId");

                    b.ToTable("DraftFeedbacks");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.InboxEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BodyText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SenderEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ThreadId")
                        .HasColumnType("text");

                    b.Property<string>("WebhookCallbackPath")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InboxEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssignedRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("CompanyId", "Email");

                    b.ToTable("Invitations");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ChunkType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("EmbeddingVector")
                        .HasColumnType("vector(1536)");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Title", "RawContent" });

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("EmbeddingVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("EmbeddingVector"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("EmbeddingVector"), new[] { "vector_cosine_ops" });

                    b.HasIndex("SearchVector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.ToTable("KnowledgeBases");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("IndexedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("KnowledgeBaseDocuments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<Vector>("CaptionEmbedding")
                        .HasColumnType("vector(1536)");

                    b.Property<Guid?>("ChunkId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CaptionEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("CaptionEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("CaptionEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("ChunkId");

                    b.HasIndex("DocumentId");

                    b.ToTable("KnowledgeBaseImages");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.MailboxConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConnectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("N8nCredentialId")
                        .HasColumnType("text");

                    b.Property<string>("N8nWorkflowId")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "EmailAddress")
                        .IsUnique();

                    b.ToTable("MailboxConnections");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("UserId");

                    b.HasIndex("CompanyId", "ModuleDefinitionId", "DepartmentId", "UserId", "Scope");

                    b.ToTable("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOperational")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("ModuleDefinitions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 597, DateTimeKind.Utc).AddTicks(2065),
                            Description = "",
                            DisplayName = "Doc-Intel",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "doc-intel",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3108),
                            Description = "",
                            DisplayName = "Finance-Flow",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "finance-flow",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3157),
                            Description = "",
                            DisplayName = "Inbox-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "inbox-guardian",
                            Tier = "Utility",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3187),
                            Description = "",
                            DisplayName = "Lead-Qualifier",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "lead-qualifier",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3216),
                            Description = "",
                            DisplayName = "Legal-Scribe",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "legal-scribe",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3244),
                            Description = "",
                            DisplayName = "Data-Guardian",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "data-guardian",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3273),
                            Description = "",
                            DisplayName = "SOP-Generator",
                            IsActive = true,
                            IsOperational = false,
                            IsPremium = false,
                            Key = "sop-generator",
                            Tier = "Industry",
                            Visibility = "UserFacing"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3304),
                            Description = "",
                            DisplayName = "Metered-Billing",
                            IsActive = true,
                            IsOperational = true,
                            IsPremium = false,
                            Key = "metered-billing",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            Category = "Utility",
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 612, DateTimeKind.Utc).AddTicks(3334),
                            Description = "",
                            DisplayName = "Audit-Log",
                            IsActive = true,
                            IsOperational = true,
                            IsPremium = false,
                            Key = "audit-log",
                            Tier = "Shadow",
                            Visibility = "Restricted"
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanConfigure")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManageIntegrations")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanManagePrompts")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanTest")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUse")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanView")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanViewLogs")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModuleAssignmentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleAssignmentId");

                    b.ToTable("ModulePermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanEntitlements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxApiRequestsPerDay")
                        .HasColumnType("integer");

                    b.Property<int>("MaxKnowledgeBases")
                        .HasColumnType("integer");

                    b.Property<int>("MaxMonthlyTokens")
                        .HasColumnType("integer");

                    b.Property<int>("MaxStorageMb")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanTemplateId")
                        .IsUnique();

                    b.ToTable("PlanEntitlements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 500,
                            MaxKnowledgeBases = 1,
                            MaxMonthlyTokens = 50000,
                            MaxStorageMb = 100,
                            PlanTemplateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 1000,
                            MaxKnowledgeBases = 5,
                            MaxMonthlyTokens = 100000,
                            MaxStorageMb = 500,
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 5000,
                            MaxKnowledgeBases = 25,
                            MaxMonthlyTokens = 500000,
                            MaxStorageMb = 5120,
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 20000,
                            MaxKnowledgeBases = 100,
                            MaxMonthlyTokens = 2000000,
                            MaxStorageMb = 51200,
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MaxApiRequestsPerDay = 100000,
                            MaxKnowledgeBases = 1000,
                            MaxMonthlyTokens = 10000000,
                            MaxStorageMb = 512000,
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanModuleInclusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ModuleDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlanTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ModuleDefinitionId");

                    b.HasIndex("PlanTemplateId", "ModuleDefinitionId")
                        .IsUnique();

                    b.ToTable("PlanModuleInclusions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1d5d43dc-c37a-4c8a-827c-ee6e0ccefd72"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 664, DateTimeKind.Utc).AddTicks(4579),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("69bae2de-8eb3-46f7-954a-bb834ee8cc82"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8106),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("73eecd08-6438-42fb-be9d-ac94d80510ed"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8135),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb")
                        },
                        new
                        {
                            Id = new Guid("5e9044bf-a66e-4b12-a7da-8519bf61c992"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8158),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("fa6896b6-8c7e-482d-8f01-4a46121701ec"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8184),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("9a6ef5fd-df2d-4f08-915c-b9111c69adeb"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8207),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("b130c2a1-c7f1-4396-a95c-04549a99639f"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8232),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc")
                        },
                        new
                        {
                            Id = new Guid("75923ec8-907d-49e2-adaa-8415060f9bd5"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8256),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("eb3f0ab8-ebbc-40ef-91b1-c5765ab7e838"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8281),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("3f71c390-df32-4162-ad11-f5dd29d07a68"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8306),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("4da1ef92-6f77-40fe-86e4-10e0c6449fc0"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8365),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("bfd6a1a1-0a5f-4039-a4b7-ab262cff8063"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8390),
                            ModuleDefinitionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("9c1148e1-df79-4d38-a581-b2af85c42c46"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8415),
                            ModuleDefinitionId = new Guid("77777777-7777-7777-7777-777777777777"),
                            PlanTemplateId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd")
                        },
                        new
                        {
                            Id = new Guid("f11a7213-83cd-41e2-8393-cdb402fb8c0d"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8441),
                            ModuleDefinitionId = new Guid("33333333-3333-3333-3333-333333333333"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("43719c9d-0422-452b-ab86-0f50c70d3803"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8466),
                            ModuleDefinitionId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("0cab4a3f-180e-4672-b56c-73e1625cf4ac"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8490),
                            ModuleDefinitionId = new Guid("44444444-4444-4444-4444-444444444444"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("c39de785-3818-48c5-bcb2-41e02c016b8f"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8516),
                            ModuleDefinitionId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("6ed4ddcf-b763-4b6b-a1de-eb63e08e80a3"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8541),
                            ModuleDefinitionId = new Guid("55555555-5555-5555-5555-555555555555"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("7d53516a-d145-41a6-8c8f-1cec5d7cd428"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8566),
                            ModuleDefinitionId = new Guid("77777777-7777-7777-7777-777777777777"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        },
                        new
                        {
                            Id = new Guid("04cf6acd-fcc6-4418-842b-38e9e04122f8"),
                            CreatedAt = new DateTime(2026, 4, 2, 6, 43, 31, 666, DateTimeKind.Utc).AddTicks(8591),
                            ModuleDefinitionId = new Guid("66666666-6666-6666-6666-666666666666"),
                            PlanTemplateId = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee")
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("BillingInterval")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTrialAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LegacyLocked")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyPriceCents")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TrialDays")
                        .HasColumnType("integer");

                    b.Property<int>("YearlyPriceCents")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("PlanTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For individuals testing AI workflows.",
                            IsActive = true,
                            IsFree = true,
                            IsTrialAllowed = false,
                            LegacyLocked = false,
                            MaxSeats = 2,
                            MonthlyPriceCents = 0,
                            Name = "Free",
                            Slug = "free",
                            TrialDays = 0,
                            YearlyPriceCents = 0
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For small teams automating support.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 5,
                            MonthlyPriceCents = 2900,
                            Name = "Starter",
                            Slug = "starter",
                            TrialDays = 14,
                            YearlyPriceCents = 29000
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For growing teams needing more power.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 25,
                            MonthlyPriceCents = 9900,
                            Name = "Growth",
                            Slug = "growth",
                            TrialDays = 14,
                            YearlyPriceCents = 99000
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            BillingInterval = "Monthly",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For large teams with advanced needs.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = true,
                            LegacyLocked = false,
                            MaxSeats = 100,
                            MonthlyPriceCents = 29900,
                            Name = "Business",
                            Slug = "business",
                            TrialDays = 14,
                            YearlyPriceCents = 299000
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            BillingInterval = "Custom",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "For large organizations with custom needs.",
                            IsActive = true,
                            IsFree = false,
                            IsTrialAllowed = false,
                            LegacyLocked = false,
                            MonthlyPriceCents = 0,
                            Name = "Enterprise",
                            Slug = "enterprise",
                            TrialDays = 0,
                            YearlyPriceCents = 0
                        });
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WebhookSecret")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UsageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModuleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "MetricType", "OccurredAt");

                    b.ToTable("UsageEvents");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .HasColumnType("text");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CompanyRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("InvitedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InvitedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserId", "CompanyId")
                        .IsUnique();

                    b.ToTable("UserCompanyMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserCompanyMembershipId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserCompanyMembershipId");

                    b.HasIndex("UserId", "CompanyId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("UserDepartmentMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenUsage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("WorkflowLogs");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.WorkflowPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoExecute")
                        .HasColumnType("boolean");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ConfidenceThreshold")
                        .HasColumnType("numeric");

                    b.Property<string>("ExcludedKeywords")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("WorkflowPolicies");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ActionRequest", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.InboxEvent", "InboxEvent")
                        .WithMany()
                        .HasForeignKey("InboxEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InboxEvent");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.CompanySubscription", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PendingPlan")
                        .WithMany()
                        .HasForeignKey("PendingPlanId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithMany("CompanySubscriptions")
                        .HasForeignKey("PlanTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("PendingPlan");

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.DraftFeedback", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ActionRequest", null)
                        .WithMany()
                        .HasForeignKey("ActionRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Invitation", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Company");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBase", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.KnowledgeBaseDocument", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Document");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseImage", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.KnowledgeBase", "Chunk")
                        .WithMany()
                        .HasForeignKey("ChunkId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OrvixFlow.Core.Entities.KnowledgeBaseDocument", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Chunk");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.MailboxConnection", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("OrvixFlow.Core.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("Assignments")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("ModuleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("ModuleDefinition");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModulePermissionGrant", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ModuleAssignment", "ModuleAssignment")
                        .WithMany("PermissionGrants")
                        .HasForeignKey("ModuleAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleAssignment");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanEntitlements", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithOne("Entitlements")
                        .HasForeignKey("OrvixFlow.Core.Entities.PlanEntitlements", "PlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanModuleInclusion", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.ModuleDefinition", "ModuleDefinition")
                        .WithMany("PlanInclusions")
                        .HasForeignKey("ModuleDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.PlanTemplate", "PlanTemplate")
                        .WithMany("ModuleInclusions")
                        .HasForeignKey("PlanTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModuleDefinition");

                    b.Navigation("PlanTemplate");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("CompanyMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserDepartmentMembership", b =>
                {
                    b.HasOne("OrvixFlow.Core.Entities.Tenant", "Company")
                        .WithMany("UserDepartmentMemberships")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.Department", "Department")
                        .WithMany("UserMemberships")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OrvixFlow.Core.Entities.UserCompanyMembership", null)
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserCompanyMembershipId");

                    b.HasOne("OrvixFlow.Core.Entities.User", "User")
                        .WithMany("DepartmentMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Department", b =>
                {
                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.KnowledgeBaseDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleAssignment", b =>
                {
                    b.Navigation("PermissionGrants");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.ModuleDefinition", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("PlanInclusions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.PlanTemplate", b =>
                {
                    b.Navigation("CompanySubscriptions");

                    b.Navigation("Entitlements");

                    b.Navigation("ModuleInclusions");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.Tenant", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("ModuleAssignments");

                    b.Navigation("UserDepartmentMemberships");

                    b.Navigation("UserMemberships");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.User", b =>
                {
                    b.Navigation("CompanyMemberships");

                    b.Navigation("DepartmentMemberships");

                    b.Navigation("ModuleAssignments");
                });

            modelBuilder.Entity("OrvixFlow.Core.Entities.UserCompanyMembership", b =>
                {
                    b.Navigation("DepartmentMemberships");
                });
#pragma warning restore 612, 618
        }
    }
}
